<?php
// $Id: services_oauth.install,v 1.2 2009/05/08 22:00:14 hugowetterberg Exp $

/**
 * Implementation of hook_install().
 */
function services_oauth_install() {
  drupal_install_schema('services_oauth');
}

/**
 * Implementation of hook_uninstall().
 */
function services_oauth_uninstall() {
  drupal_uninstall_schema('services_oauth');
}

/**
 * Implementation of hook_schema().
 */
function services_oauth_schema() {
  $schema = array();

  return $schema;
}